PizzaBundle\Entity\Type:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Type, Details]
    name:
      expose: true
      groups: [Type, External, Details]
    products:
      expose: true
      groups: [External, Details]
      type: ArrayCollection<PizzaBundle\Entity\Product>
      max_depth: 1


