PizzaBundle\Entity\Product:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Product, Details]
    name:
      expose: true
      groups: [Product, Details]
    description:
      expose: true
      groups: [Product, Details]
    available:
      expose: true
      groups: [Product, Details]
    prices:
      expose: true
      groups: [Price, Details]
      type: ArrayCollection<PizzaBundle\Entity\Price>
      max_depth: 1

