PizzaBundle\Entity\Price:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Price, Details]
    type:
      expose: true
      groups: [Price, Details]
    value:
      expose: true
      groups: [Price, Details]

