PizzaBundle\Entity\Item:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Item, Details]
    productId:
      expose: true
      groups: [Item, Details]
    productName:
      expose: true
      groups: [Item, Details]
    productDescription:
      expose: true
      groups: [Item, Details]
    productType:
      expose: true
      groups: [Item, Details]
    productPrice:
      expose: true
      groups: [Item, Details]

