PizzaBundle\Entity\Order:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Order, Details]
    createDate:
      expose: true
      groups: [Order, Details]
    realized:
      expose: true
      groups: [Order, Details]
    description:
      expose: true
      groups: [Order, Details]
    totalPrice:
      expose: true
      groups: [Order, Details]
    promoCode:
      expose: true
      groups: [Order, Details]
    promoCodeType:
      expose: true
      groups: [Order, Details]
    promoCodeValue:
      expose: true
      groups: [Order, Details]
    customerFirstName:
      expose: true
      groups: [Order, Details]
    customerLastName:
      expose: true
      groups: [Order, Details]
    customerEmail:
      expose: true
      groups: [Order, Details]
    customerPhone:
      expose: true
      groups: [Order, Details]
    customerAddress:
      expose: true
      groups: [Order, Details]
    items:
      expose: true
      groups: [Item, Details]
      type: ArrayCollection<PizzaBundle\Entity\Item>
      max_depth: 1
    customer:
      expose: true
      groups: [Customer, Details]
      type: PizzaBundle\Entity\Customer
      max_depth: 1
    promoCode:
      expose: true
      groups: [Customer, Details]
      type: PizzaBundle\Entity\PromoCode
      max_depth: 1