PizzaBundle\Entity\Application:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [Application, External, Details]
    name:
      expose: true
      groups: [Application, External, Details]
    description:
      expose: true
      groups: [Application, External, Details]
    homepage:
      expose: true
      groups: [Application, Details]
    demo:
      expose: true
      groups: [Application, Details]
    createDate:
      expose: true
      groups: [Application, Details]
    types:
      expose: true
      groups: [External, Details]
      type: ArrayCollection<PizzaBundle\Entity\Type>
      max_depth: 1
