imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@PizzaBundle/Resources/config/services.yml" }

parameters:
    locale: en

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    encryption: "ssl"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }


bazinga_hateoas: ~

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUserBundle/"

fos_rest:
    param_fetcher_listener: true
    disable_csrf_role: ROLE_API
    service:
        serializer: jms_serializer.serializer
    serializer:
        serialize_null: true
    routing_loader:
        default_format: json
    view:
        view_response_listener: 'force'
        serialize_null: true
        formats:
            json: true
            xml:  true

nelmio_api_doc: ~

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
        '^/ext/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            max_age: 3600
        '^/oauth/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: OAuthBundle\Entity\User

fos_oauth_server:
    db_driver: orm
    client_class:        OAuthBundle\Entity\Client
    access_token_class:  OAuthBundle\Entity\AccessToken
    refresh_token_class: OAuthBundle\Entity\RefreshToken
    auth_code_class:     OAuthBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager
        options:
            access_token_lifetime: 3600

fsi_admin:
    templates:
        base: "::admin.html.twig"