PizzaBundle\Entity\EmailNotification:
    type: entity
    table: email_notification
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 50
            options:
              fixed: false
        email:
            column: email
            type: string
            nullable: false
            length: 50
            options:
              fixed: false
        active:
            column: active
            type: boolean
            options:
                default: 0
    manyToOne:
        application:
            targetEntity: Application
            inversedBy: email_notification
            joinColumn:
                    name: application_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }