PizzaBundle\Entity\Item:
    type: entity
    table: item
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productId:
            column: product_id
            type: integer
        productName:
            column: product_name
            type: string
        productDescription:
            column: product_description
            type: string
        productType:
                    column: product_type
                    type: string
        productPrice:
            column: product_price
            type: decimal
            precision: 10
            scale: 2
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: item
            joinColumn:
                    name: order_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }