PizzaBundle\Entity\Order:
    type: entity
    table: _order
    repositoryClass: PizzaBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createDate:
            column: create_date
            type: datetime
            nullable: false
        realized:
            column: realized
            type: boolean
            options:
                default: 0
        description:
            column: description
            type: string
            nullable: true
            length: 800
            options:
              fixed: false
        totalPrice:
            column: total_price
            type: decimal
            precision: 10
            scale: 2
        promoCode:
            column: promo_code
            type: string
            nullable: true
            length: 20
            options:
              fixed: false
        promoCodeType:
            column: promo_code_type
            type: string
            nullable: true
            length: 20
            options:
              fixed: false
        promoCodeValue:
            column: promo_code_value
            type: string
            nullable: true
            length: 20
            options:
              fixed: false
        customerFirstName:
            column: customer_first_name
            type: string
            nullable: false
            length: 50
            options:
              fixed: false
        customerLastName:
            column: customer_last_name
            type: string
            nullable: false
            length: 50
            options:
              fixed: false
        customerEmail:
            column: customer_email
            type: string
            nullable: false
            length: 50
            options:
              fixed: false
        customerPhone:
            column: customer_phone
            type: string
            nullable: false
            length: 50
            options:
              fixed: false
        customerAddress:
            column: customer_address
            type: string
            nullable: false
            length: 200
            options:
              fixed: false
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: order
            cascade: ["all"]
    manyToOne:
        application:
            targetEntity: Application
            inversedBy: order
            joinColumn:
                    name: application_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }