PizzaBundle\Entity\Type:
    type: entity
    table: type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 20
            options:
              fixed: false
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: type
            cascade: ["all"]
    manyToOne:
        application:
            targetEntity: Application
            inversedBy: type
            joinColumn:
                    name: application_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }