OAuthBundle\Entity\AccessToken:
  type: entity
  table: accesstoken
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    client:
      targetEntity: PGS\OAuthBundle\Entity\Client
      joinColumn:
        nullable: false
    user:
      targetEntity: PGS\OAuthBundle\Entity\User

  lifecycleCallbacks: {  }
