OAuthBundle\Entity\User:
  type: entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  manyToOne:
    application:
        targetEntity: PizzaBundle\Entity\Application
        inversedBy: fos_user
        joinColumn:
            name: application_id
            referencedColumnName: id
  lifecycleCallbacks: {  }
