api_users:
  prefix: /user/
  resource: "@ApiBundle/Resources/config/api/user.yml"

api_application:
  resource: "@ApiBundle/Resources/config/api/application.yml"

api_products:
  resource: "@ApiBundle/Resources/config/api/product.yml"

api_type:
  resource: "@ApiBundle/Resources/config/api/type.yml"