api_users:
  prefix: /user/
  resource: "@ApiBundle/Resources/config/api/user.yml"

api_application:
  resource: "@ApiBundle/Resources/config/api/application.yml"

api_products:
  resource: "@ApiBundle/Resources/config/api/product.yml"

api_type:
  resource: "@ApiBundle/Resources/config/api/type.yml"

api_price:
  resource: "@ApiBundle/Resources/config/api/price.yml"

api_promocode:
  resource: "@ApiBundle/Resources/config/api/promocode.yml"

api_customer:
  resource: "@ApiBundle/Resources/config/api/customer.yml"

api_order:
  resource: "@ApiBundle/Resources/config/api/order.yml"

api_email:
  resource: "@ApiBundle/Resources/config/api/email.yml"