services:
  client_validate:
    class: ApiBundle\Validator\Constraints\ClientIdValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      -  { name: validator.constraint_validator, alias: client_validate }

  user_validate:
    class: ApiBundle\Validator\Constraints\UserUniqueValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      -  { name: validator.constraint_validator, alias: user_validate }

  product_voter:
    class: ApiBundle\Security\Authorization\Voter\ProductVoter
    tags:
      - { name: security.voter }
    public: false

  customer_voter:
    class: ApiBundle\Security\Authorization\Voter\CustomerVoter
    tags:
      - { name: security.voter }
    public: false

  order_voter:
    class: ApiBundle\Security\Authorization\Voter\OrderVoter
    tags:
      - { name: security.voter }
    public: false

  price_voter:
    class: ApiBundle\Security\Authorization\Voter\PriceVoter
    tags:
      - { name: security.voter }
    public: false

  promocode_voter:
    class: ApiBundle\Security\Authorization\Voter\PromoCodeVoter
    tags:
      - { name: security.voter }
    public: false

  type_voter:
    class: ApiBundle\Security\Authorization\Voter\TypeVoter
    tags:
      - { name: security.voter }
    public: false

  email_notification_voter:
    class: ApiBundle\Security\Authorization\Voter\EmailNotificationVoter
    tags:
      - { name: security.voter }
    public: false

  sms_notification_voter:
    class: ApiBundle\Security\Authorization\Voter\SmsNotificationVoter
    tags:
      - { name: security.voter }
    public: false