api_customer_index:
  path: customers.{_format}
  defaults:  { _controller: ApiBundle:Customer:index, _format: json }
  methods: [GET]

api_customer_show:
  path: customers/{customer_id}.{_format}
  defaults:  { _controller: ApiBundle:Customer:show, _format: json }
  methods: [GET]

api_customer_delete:
  path: customers/{customer_id}.{_format}
  defaults:  { _controller: ApiBundle:Customer:delete, _format: json }
  methods: [DELETE]