services:
  pizza.type.factory:
    class: PizzaBundle\Model\TypeFactory

  pizza.customer.factory:
    class: PizzaBundle\Model\CustomerFactory

  pizza.order.factory:
    class: PizzaBundle\Model\OrderFactory

  pizza.item.factory:
    class: PizzaBundle\Model\ItemFactory
    arguments:
      entityManager: "@doctrine.orm.entity_manager"

  pizza.customer.repository:
      class: Doctrine\ORM\EntityRepository
      factory: [@doctrine.orm.entity_manager, getRepository]
      arguments:
        - PizzaBundle\Entity\Customer

  pizza.order.repository:
      class: Doctrine\ORM\EntityRepository
      factory: [@doctrine.orm.entity_manager, getRepository]
      arguments:
        - PizzaBundle\Entity\Order

  promo.code.type.validate:
      class: PizzaBundle\Validator\Constraints\PromoCodeTypeValidator
      tags:
        -  { name: validator.constraint_validator, alias: promo_code_type_validate }

  promo.code.unique.validate:
      class: PizzaBundle\Validator\Constraints\PromoCodeUniqueValidator
      arguments:
            entityManager: "@doctrine.orm.entity_manager"
            security: @security.token_storage
      tags:
        -  { name: validator.constraint_validator, alias: promo_code_unique_validate }

  pizza.promo_code.business:
    class: PizzaBundle\Model\PromoCodeBusiness
    arguments:
      entityManager: "@doctrine.orm.entity_manager"

  pizza.email_notification.repository:
     class: Doctrine\ORM\EntityRepository
     factory: [@doctrine.orm.entity_manager, getRepository]
     arguments:
       - PizzaBundle\Entity\EmailNotification

  pizza.email_notification.strategy:
    class: PizzaBundle\Notification\Strategies\EmailStrategy
    arguments:
      emailNotificationRepository: "@pizza.email_notification.repository"
      twig: "@twig"
      mailer: "@mailer"

  pizza.sms_notification.repository:
     class: Doctrine\ORM\EntityRepository
     factory: [@doctrine.orm.entity_manager, getRepository]
     arguments:
       - PizzaBundle\Entity\SmsNotification

  pizza.sms_notification.strategy:
    class: PizzaBundle\Notification\Strategies\SmsStrategy
    arguments:
      smsNotificationRepository: "@pizza.sms_notification.repository"

  pizza.notification.strategy.factory:
    class: PizzaBundle\Notification\StrategiesFactory
    arguments:
      emailStrategy: "@pizza.email_notification.strategy"
      smsStrategy: "@pizza.sms_notification.strategy"