ext_get_appliacation:
  path: get/{application_id}.{_format}
  defaults:  { _controller: ExternalApiBundle:GetApplication:show, _format: json }
  methods: [GET]

ext_order:
  path: order/{application_id}.{_format}
  defaults:  { _controller: ExternalApiBundle:CompleteOrder:create, _format: json }
  methods: [POST]

ext_check_promo_code:
  path: promocode/{application_id}.{_format}
  defaults:  { _controller: ExternalApiBundle:CheckPromoCode:check, _format: json }
  methods: [POST]