---
- name: Install python-pycurl
  apt: pkg=python-pycurl state=latest
#
#- name: Add php repository
#  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php5-oldstable/ubuntu precise main' state=present
#
#- name: Add php repository key
#  apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C state=present

- name: Install PHP 
  apt: name=php5 state=latest force=yes

- name: Intsall PHP packages
  apt: name={{ item }} state=latest force=yes
  with_items:
    - php-apc
    - php5-cli
    - php5-gd
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-pgsql

- name: Configure PHP
  template: src=php_config.ini.j2 dest=/etc/php5/apache2/conf.d/php_config.ini force=yes
